### ISSUE TITLE
关于代码的细节问题

### ISSUE THREAD

**Issue by xpyqiubai** [yxgeee/SpCL#12]
想像您请教一下代码这个函数
def compute_jaccard_distance(target_features, k1=20, k2=6, print_flag=True, search_option=0, use_float16=False):
这里的k1 k2的物理意义是什么，或者说这个参数控制了什么，这里看您设置的是30和6，如果改变这些参数会对最后结果产生什么影响。谢谢您

**Comment by yxgeee** [comment]
你好，Jaccard distance的计算方法及k1/k2的含义请参考reranking person re-identification with k-reciprocal encoding：https://openaccess.thecvf.com/content_cvpr_2017/papers/Zhong_Re-Ranking_Person_Re-Identification_CVPR_2017_paper.pdf
我们在SpCL的所有实验中都是用k1=30,k2=6这个设置，如果针对具体数据集调整参数，可以获得性能提升。比如，在duke->market的时候使用k1=20,k2=6可以提升2个点左右的mAP。
