### ISSUE TITLE
Performance improvements compared to the original version

### ISSUE THREAD

**Issue by hjwang-824** [yxgeee/SpCL#14]
Hi, I noticed that the USL performances on Market1501 dataset of your original arxiv version (mAP:72.6%) are slightly lower than that of your NeurIPS-2020 camera-ready version (mAP:73.1%), have you used some extral tricks? And what contributes to the amazing performance improvements of the OpenUnReID SpCL+ version compared to your original SpCL version? Thank you!

**Comment by yxgeee** [comment]
Hi,

No extra tricks, just randomness. I have re-trained it several times and
the performances were all above 73%, so I used 73.1% in the final version.
The only difference between SpCL+ (OpenUnReID) and SpCL in this repo is
that SpCL+ adopts GeM pooling while SpCL adopts average pooling.

Best

Haijian Wang <notifications@github.com>于2020年10月20日 周二17:39写道：
