### ISSUE TITLE
about the python version and numpy version

### ISSUE THREAD

**Issue by ShiMinghao0208** [yxgeee/SpCL#17]
![image](https://user-images.githubusercontent.com/53176521/98086695-12050000-1eba-11eb-9eb9-7e62f0012675.png)
i try to update numpy，but it still existed this mistake.
I don't know if I need to recompile your Github code or other reasons

**Comment by yxgeee** [comment]
It seems the issue with your `numpy` package. Try:
```
pip uninstall numpy
conda install numpy
```

**Comment by ShiMinghao0208** [comment]
> It seems the issue with your `numpy` package. Try:
> 
> ```
> pip uninstall numpy
> conda install numpy
> ```
This did solve it, thank you very much and sorry to disturb you
