### ISSUE TITLE
The update of source feature in hybrid memory

### ISSUE THREAD

**Issue by kuiran** [yxgeee/SpCL#23]
In your paper, "For the source-domain class centroids {w}, the k-th centroid wk is updated by the mean of the encoded features belonging to class k in the mini-batch."
But where is the mean operation in your code?

**Comment by yxgeee** [comment]
In practice, I found that updating the centroids by the mean of the features is almost equal to updating the centroids by the corresponding features sequentially, achieving similar performances. So I use the latter one for brevity.

**Comment by kuiran** [comment]
Okay, thank you!
