### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by sunxia233** [yxgeee/SpCL#24]
Hi, great work!
Can  you explain this line of code
sim /= (mask*nums+(1-mask)).clone().expand_as(sim)
I did not understand its meaning.

**Comment by yxgeee** [comment]
`mask` is used to handle the discontinuous label set, e.g. there's no sample for class no.5.
`sim/nums` denotes the similarities between each sample and the centroids.

**Comment by yxgeee** [comment]
I will close the issue as no more response is shown.
