### ISSUE TITLE
Loss cannot be converged

### ISSUE THREAD

**Issue by CWF-999** [yxgeee/SpCL#25]
During the training process, loss_s can quickly converge, but Loss_t has been maintained between 8-9. What could be the reason for this?

**Comment by yxgeee** [comment]
Yes. As I remember, the value of loss_t is larger than loss_s due to more classes (clusters+outliers) for the target domain. But it would not affect the final results. How's your training performance?

**Comment by yxgeee** [comment]
I will close the issue as no more response is shown.
