### ISSUE TITLE
TypeError: in method 'bruteForceKnn', argument 12 of type 'faiss::Index::idx_t *'

### ISSUE THREAD

**Issue by luckycookiecookie** [yxgeee/SpCL#26]
hi，there are some problem
![image](https://user-images.githubusercontent.com/20705810/103520192-b8b54f00-4eb1-11eb-9b8e-1f115e466d1d.png)

**Comment by yxgeee** [comment]
Did you figure it out? It seems the issue with `faiss` package. Please use `faiss_gpu==1.6.3`.
