### ISSUE TITLE
number of instances in each mini batch

### ISSUE THREAD

**Issue by ZacharyWang-007** [yxgeee/SpCL#27]
Hi Yixiao, I have conducted several experiments by running ur code, finding that when setting the number of instances 0, the accuracy drops a lot. Have u found out this before?
Theoretically, the Sampler should be such crucial to the Re-ID task. 
Could u please explain for me?

**Comment by yxgeee** [comment]
Yes, PxK sampler is critical to re-ID tasks, including supervised and unsupervised. And I think such a sampler also works for other fine-grained recognition tasks. Since it mainly targets at providing more intra-/inter-class information for training.
