### ISSUE TITLE
`fassi-gpu` version should be fixed below `v1.6.4`

### ISSUE THREAD

**Issue by ckmessi** [yxgeee/SpCL#28]
After installing dependencies according to the guidance, we encountered a runtime error about `fassi`:
```
AttributeError: module 'faiss' has no attribute 'cast_integer_to_long_ptr'
```

Search these keywords in Google can not get any relative answers.

By analyzing the source code of [Faiss](https://github.com/facebookresearch/faiss), we found that from version `v1.6.5` the method `cast_integer_to_long_ptr` disappeared.

So the `fassi-gpu` lib should be fixed below version `v1.6.4`, just as the [commit](https://github.com/open-mmlab/OpenUnReID/commit/900b7bc3adc77b545d6c167c4288f9372c5e99d3#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552)  in OpenUnReID did.

a very simple PR https://github.com/yxgeee/SpCL/pull/29 has been created.

**Comment by yxgeee** [comment]
Update done. Thanks!

**Comment by ckmessi** [comment]
> Update done. Thanks!

Nice, so quickly!
