### ISSUE TITLE
Question about the paper 

### ISSUE THREAD

**Issue by Liam501** [yxgeee/SpCL#30]
Hi, In your paper “Self-paced Contrastive Learning with Hybrid Memory for Domain Adaptive Object Re-ID”, there was one particular place that gets me a little bit confuse. 
![image](https://user-images.githubusercontent.com/31317371/105669439-3f41d700-5f1a-11eb-8cd1-2d2a017174ee.png)
In Table 5(a), there is a huge improvement in mAP and CMC when using self-paced learning strategy. However,  there is still a large gap between Src. class + tgt. cluster (w/o self-paced) and Ours w/o R_comp & R_indep. Can you explain more about self-paced learning strategy, does that means using R_comp & R_indep?

**Comment by yxgeee** [comment]
1. The difference between `Src. class + tgt. cluster (w/o self-paced)` and `Ours w/o R_comp & R_indep` is that, `Src. class + tgt. cluster (w/o self-paced)` does not use outliers for training while `Ours w/o R_comp & R_indep` uses outliers for joint training.
2. Yes, `self-paced` means `R_comp & R_indep`.

**Comment by Liam501** [comment]
Okey, now I understand it. Thank you for answering my question.
