### ISSUE TITLE
hello, anyone meet this error?

### ISSUE THREAD

**Issue by Bobo-y** [yxgeee/SpCL#39]
Computing jaccard distance...
bruteForceKnn is deprecated; call bfKnn instead
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runL2Norm(faiss::gpu::Tensor<T, 2, true, IndexType>&, bool, faiss::gpu::Tensor<float, 1, true, IndexType>&, bool, cudaStream_t) [with T = float; TVec = float4; IndexType = int; cudaStream_t = CUstream_st*] at gpu/impl/L2Norm.cu:292; details: CUDA error 11 invalid argument
Aborted (core dumped)

env info:

torch1.7.0
cuda11.1
2080TI

**Comment by pSGAme** [comment]
Hello, i met this problem too. Can you tell me how you solve this problem? plz....

**Comment by Bobo-y** [comment]
emmmm, sorry, forget .....llong time ago

**Comment by pSGAme** [comment]
> emmmm, sorry, forget .....llong time ago

hao ba~~~

**Comment by m250317460** [comment]
> > emmmm, sorry, forget .....llong time ago
> 
> hao ba~~~

Have you deal this problem?

**Comment by Lun-Wang** [comment]
Have you deal this problem?

**Comment by m250317460** [comment]
> Have you deal this problem?

No,i gave up it.

**Comment by Emersonzc** [comment]
TRY
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2

**Comment by Emersonzc** [comment]
> TRY conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2

2080 driver version 515
