### ISSUE TITLE
A question about len(cluster_R_indep)

### ISSUE THREAD

**Issue by zengkaiwei** [yxgeee/SpCL#7]
In spcl_train_uda.py line 245:
pseudo_labels[i] = source_classes+len(cluster_R_indep)+outliers
why is len(cluster_R_indep)?
Your propose is just to distinguish outliers and inliers(It seems change the value of len(cluster_R_indep) to a enough big constant won't effect model performance)?

**Comment by yxgeee** [comment]
As described in our paper, we treat each outlier sample as an individual class.
