### ISSUE TITLE
about personx dataset

### ISSUE THREAD

**Issue by darcyzhc** [yxgeee/SpCL#8]
In spcl/datasets/personx.py, it shows that `# images: 9840 (train) + 5136 (query) + 30816 (gallery)`, I just find the personx_v1 dataset in https://github.com/sxzrt/Instructions-of-the-PersonX-dataset, but this train number and query number doesn't match the code. And the camera id doesn't match too. So I want to know which version of `personx` did you use?

**Comment by yxgeee** [comment]
I use “A more chanllenging subset of PersonX” of personx.

darcy <notifications@github.com>于2020年8月1日 周六16:23写道：

**Comment by darcyzhc** [comment]
Thanks. Is there any download link of this dataset?

**Comment by yxgeee** [comment]
https://github.com/sxzrt/Instructions-of-the-PersonX-dataset#a-more-chanllenging-subset-of-personx

**Comment by darcyzhc** [comment]
Yeah, this is what I used. There are 6 subset folder.  Each subset folder has 3 part: `bounding_box_test` , `bounding_box_train`  and `query`, each `query` contains 856 images, each `bounding_box_test` contains 30,816 images and `bounding_box_train` contains 14,760 images. This doesn't match with the code.

**Comment by yxgeee** [comment]
Please carefully look at the link provided. “#a-more-chanllenging-subset-of-personx”

**Comment by darcyzhc** [comment]
There two link:
```
Data of cvpr19
3D identetie models of PersonX and images of above 6 backgrounds can be downloaded from the following links:

Baidu Yun Drive:
3d model of person link
images of six backgrounds link (First one)
```

```
A more chanllenging subset of PersonX
This datatet also contains 6 cameras, but it is more chanllending than the data used in CVPR19. We add occlusion, different resolution and illumination in this subset.

Baidu Yun Drive:
images link (code:g2q5) (Second one)
```
And the two link is identity, which doesn't match the code.
Could you give a Baidu Yun Drive link or a Google Drive link?

**Comment by darcyzhc** [comment]
OK, I figure out. The Baidu Yun Drive link of  “#a-more-chanllenging-subset-of-personx” is wrong, and the Google Drive link is right.

**Comment by yxgeee** [comment]
Good!
