### ISSUE TITLE
gpu ram and batch_size

### ISSUE THREAD

**Issue by r07942156** [yxgeee/SpCL#9]
Thank you for releasing the code!
Because I have only one 2080s GPU, I am wondering how much gup-ram does 
`CUDA_VISIBLE_DEVICES=0 python examples/spcl_train_uda.py -ds dukemtmc -dt market1501 --logs-dir logs/spcl_uda/duke2market_resnet50`
 need in the default setting(batch_size=64).

Another issue is will the performance drop a lot if setting batch-size=32?

**Comment by yxgeee** [comment]
Hi, I cannot remember the GPU memory cost, you can try to use `batch_size=64` first. If it is out of memory, you can modify it to `batch_size=32`. The performance may be drop without default settings, person re-ID experiments are sensitive to the number of batch size and the number of GPUs. I don't know how much would it affect when training in different settings as I did not try it before.

By the way, you can also try our [OpenUnReID](https://github.com/open-mmlab/OpenUnReID) codebase, which also supports the training of SpCL. OpenUnReID supports mixed precision training (`TRAIN.amp True`), which could save much GPU memory. So it is ok to run with batch_size=64 on a single 2080s GPU by OpenUnReID.
